---
AWSTemplateFormatVersion: "2010-09-09"
Description: 'Create Deployment Bucket'

Resources:
  DeployBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl

Outputs:
  DeployBucket:
    Description: S3 bucket name
    Value: !Ref DeployBucket