---
AWSTemplateFormatVersion: '2010-09-09'
Description: '04-lambda-golang-bucket'

Parameters:
  BucketName:
    Type: String

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled

Outputs:
  BucketName:
    Value: Ref! BucketName
  BucketArn:
    Value: !GetAtt Bucket.Arn
