#
# The open source version of the Amazon API Gateway Developer Guide is available at GitHub
# see https://github.com/awsdocs/amazon-api-gateway-developer-guide
#
swagger: '2.0'
info:
  description: Your first API with Amazon API Gateway.
  title: PetStore
  version: 1.0.0
schemes:
  - https
paths:
  /pets:
    get: # swagger operations
      summary: List all pets
      produces:
        - application/json
      responses: # swagger operations responses field
        '200':
          description: Successful operation
          headers:
            Content-Type:
              type: string
              description: Media type of request
          schema:
            $ref: '#/definitions/Pets'
      # see: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-integration.html
      x-amazon-apigateway-integration:
        #  Defines the method's responses and specifies desired parameter
        # mappings or payload mappings from integration responses to method responses.
        #
        responses:
          # see: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-integration-response.html
          default:
            statusCode: '200' # HTTP status code for the method response. This must correspond to a matching response in the Swagger Operation responses field.
            responseParameters: # Specifies parameter mappings for the response. Only the header and body parameters of the integration response can be mapped to the header parameters of the method.
              method.response.header.Content-Type: '''application/json'''
            responseTemplates: # Specifies MIME type-specific mapping templates for the response’s payload.
              application/json: |-
                [{
                  'id': '1',
                  'type': 'cat',
                  'price': 150
                },
                {
                  'id': '2',
                  'type': 'dog',
                  'price': 250
                },
                {
                  'id': '3',
                  'type': 'cat',
                  'price': 350
                }]
        passthroughBehavior: when_no_match # Specifies how a request payload of unmapped content type is passed through the integration request without modification
        requestTemplates: # Mapping templates for a request payload of specified MIME types.
          application/json: |-
            {
              "statusCode": 200
            }
        # The 'type' of integration with the specified backend,
        # 'http | http_proxy' for HTTP backend,
        # 'aws_proxy' for lambda,
        # 'aws' for lambda or other aws services,
        # 'mock' for integration with API Gateway without invoking any backend
        type: mock
definitions:
  Pets:
    type: array
    items:
      $ref: '#/definitions/Pet'
  Pet:
    type: object
    properties:
      id:
        type: string
      type:
        type: string
      price:
        type: number
# see: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-documentation.html
x-amazon-apigateway-documentation:
  version: v1.0.0 # The version identifier of the snapshot of the exported documentation parts.
  createdDate: '2016-11-17T07:03:59Z'
  documentationParts: # An array of the exported or imported DocumentationPart instances, see: https://docs.aws.amazon.com/apigateway/api-reference/resource/documentation-part/
    - location:
        type: API
      properties:
        info:
          description: >
            Your first API with Amazon API Gateway.
    - location:
        type: METHOD
        path: /pets
        method: GET
        summary: List all pets