---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Elastic Container Service - EC2'
Parameters:
  VpcId:
    Description: The id of the Vpc
    Type: String
  PublicSubnetId:
    Description: The id of the public subnet
    Type: String
  ClusterName:
    Description: The name of the ecs cluster
    Type: String

Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      DisableApiTermination: false
      ImageId: 'ami-0dbcd2533bc72c3f6'
      IamInstanceProfile: !Ref InstanceProfile
      SecurityGroupIds:
        - !Ref VpcSecurityGroup
      InstanceType: t3.small
      Monitoring: false
      SubnetId: !Ref PublicSubnetId
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum install -y https://s3-${AWS::Region}.amazonaws.com/amazon-ssm-${AWS::Region}/latest/linux_amd64/amazon-ssm-agent.rpm
          echo ECS_CLUSTER=${ClusterName} > /etc/ecs/ecs.config

  VpcSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 security group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - FromPort: 80
          ToPort: 80
          IpProtocol: tcp
          CidrIp: '0.0.0.0/0'
        - FromPort: 443
          ToPort: 443
          IpProtocol: tcp
          CidrIp: '0.0.0.0/0'
      SecurityGroupEgress:
        - IpProtocol: '-1'
          CidrIp: '0.0.0.0/0'

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleForSSM
      Policies:
        - PolicyName: ecs-service
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - ecs:CreateCluster
                  - ecs:DeregisterContainerInstance
                  - ecs:DiscoverPollEndpoint
                  - ecs:Poll
                  - ecs:RegisterContainerInstance
                  - ecs:StartTelemetrySession
                  - ecs:Submit*
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                  - firehose:DescribeDeliveryStream
                  - ec2:ModifyInstanceCreditSpecification
                Resource: '*'

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref Role

Outputs:
  PrivateIp:
    Description: The private ip address
    Value: !GetAtt Ec2Instance.PrivateIp
  PublicIp:
    Description: The public ip address
    Value: !GetAtt Ec2Instance.PublicIp
