AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      DefinitionBody:
        swagger: '2.0'
        info:
          version: '2017-02-24T04:09:00Z'
          title: echo-service
        paths:
          /{proxy+}:
            x-amazon-apigateway-any-method:
              description: handle any resource and any method
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: '200'
                uri:
                  !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${EchoFunction.Arn}/invocations
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
              responses: {}

  EchoFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: python3.6
      MemorySize: 256
      Timeout: 300
      InlineCode: |
        import json
        def handler(event, context):
          print(event)
          response = {
            'statusCode': 200,
            'body': json.dumps('Hello Python')
          }
          return response

Outputs:
  ServiceEndpoint:
    Description: API Endpoint
    Value: !Join
    - ""
    - - "https://"
      - !Ref ApiGatewayApi
      - ".execute-api."
      - !Ref AWS::Region
      - "."
      - !Ref AWS::URLSuffix
      - "/dev"

