template_path: templates/bucket.yaml
hooks:
  before_delete:
    - !cmd aws s3 rm --recursive s3://$(aws cloudformation describe-stacks --stack-name cf-dnvriend-dev-eu-west-1-bucket --query "Stacks[0].Outputs[?OutputKey=='DeployBucket'] | [0].OutputValue" --output text) || exit 0
